### sobolev kernel evalustion

In [1]:
import time
import numpy as np
import pandas as pd
import os
from tqdm import tqdm
from sklearn import metrics
from sklearn.metrics.pairwise import rbf_kernel

from goodpoints import compress
from openxai.model import LoadModel
from openxai.dataloader import ReturnLoaders
import sage
import shap

In [2]:
_, loader_test = ReturnLoaders(data_name="german", download=False, batch_size=128)
X_test = loader_test.dataset.data
y_test = loader_test.dataset.targets.to_numpy()
model = LoadModel(data_name="german", ml_model="ann", pretrained=True)
model.eval()
predictions = model.predict(X_test)

### compression

In [3]:
start_time = time.time()
compressed_indices_sobolev1 = compress.compresspp_kt(X_test, kernel_type=b"sobolev", k_params=np.array([1.0]), seed=1)
compressed_indices_sobolev1_time = time.time() - start_time

In [ ]:
X_test_sobolev1 = X_test[compressed_indices_sobolev1]
y_test_sobolev1 = y_test[compressed_indices_sobolev1]

In [20]:
start_time = time.time()
compressed_indices_sobolev3 = compress.compresspp_kt(X_test, kernel_type=b"sobolev", k_params=np.array([3.0]), seed=1)
compressed_indices_sobolev3_time = time.time() - start_time
X_test_sobolev3 = X_test[compressed_indices_sobolev3]
y_test_sobolev3 = y_test[compressed_indices_sobolev3]

### explain

In [21]:
start_time = time.time()
explainer = shap.KernelExplainer(lambda x: model.predict_proba(x)[:, 1], X_test_sobolev1, seed=1)
exp_shap_sobolev1 = explainer(X_test, silent=True).values
end_time_explanation_shap_sobolev1 = time.time() - start_time

start_time = time.time()
imputer = sage.MarginalImputer(model.predict_proba, X_test_sobolev1)
explainer = (sage.PermutationEstimator)(imputer, loss="cross entropy", random_state=1)
exp_sage_sobolev1 = explainer(X_test, y_test, bar=False, verbose=True).values
end_time_explanation_sage_sobolev1 = time.time() - start_time

StdDev Ratio = 0.1489 (Converge at 0.0250)
StdDev Ratio = 0.1073 (Converge at 0.0250)
StdDev Ratio = 0.0834 (Converge at 0.0250)
StdDev Ratio = 0.0781 (Converge at 0.0250)
StdDev Ratio = 0.0661 (Converge at 0.0250)
StdDev Ratio = 0.0615 (Converge at 0.0250)
StdDev Ratio = 0.0575 (Converge at 0.0250)
StdDev Ratio = 0.0536 (Converge at 0.0250)
StdDev Ratio = 0.0495 (Converge at 0.0250)
StdDev Ratio = 0.0470 (Converge at 0.0250)
StdDev Ratio = 0.0459 (Converge at 0.0250)
StdDev Ratio = 0.0435 (Converge at 0.0250)
StdDev Ratio = 0.0423 (Converge at 0.0250)
StdDev Ratio = 0.0410 (Converge at 0.0250)
StdDev Ratio = 0.0397 (Converge at 0.0250)
StdDev Ratio = 0.0380 (Converge at 0.0250)
StdDev Ratio = 0.0362 (Converge at 0.0250)
StdDev Ratio = 0.0349 (Converge at 0.0250)
StdDev Ratio = 0.0344 (Converge at 0.0250)
StdDev Ratio = 0.0333 (Converge at 0.0250)
StdDev Ratio = 0.0322 (Converge at 0.0250)
StdDev Ratio = 0.0319 (Converge at 0.0250)
StdDev Ratio = 0.0313 (Converge at 0.0250)
StdDev Ratio = 0.0307 (Converge at 0.0250)
StdDev Ratio = 0.0303 (Converge at 0.0250)
StdDev Ratio = 0.0298 (Converge at 0.0250)
StdDev Ratio = 0.0293 (Converge at 0.0250)
StdDev Ratio = 0.0287 (Converge at 0.0250)
StdDev Ratio = 0.0280 (Converge at 0.0250)
StdDev Ratio = 0.0275 (Converge at 0.0250)
StdDev Ratio = 0.0271 (Converge at 0.0250)
StdDev Ratio = 0.0272 (Converge at 0.0250)
StdDev Ratio = 0.0268 (Converge at 0.0250)
StdDev Ratio = 0.0268 (Converge at 0.0250)
StdDev Ratio = 0.0264 (Converge at 0.0250)
StdDev Ratio = 0.0259 (Converge at 0.0250)
StdDev Ratio = 0.0256 (Converge at 0.0250)
StdDev Ratio = 0.0252 (Converge at 0.0250)
StdDev Ratio = 0.0248 (Converge at 0.0250)
Detected convergence

In [ ]:
start_time = time.time()
explainer = shap.KernelExplainer(lambda x: model.predict_proba(x)[:, 1], X_test_sobolev3, seed=1)
exp_shap_sobolev3 = explainer(X_test, silent=True).values
end_time_explanation_shap_sobolev3 = time.time() - start_time

start_time = time.time()
imputer = sage.MarginalImputer(model.predict_proba, X_test_sobolev3)
explainer = (sage.PermutationEstimator)(imputer, loss="cross entropy", random_state=1)
exp_sage_sobolev3 = explainer(X_test, y_test, bar=False, verbose=True).values
end_time_explanation_sage_sobolev3 = time.time() - start_time

### calculate metric

In [17]:
def calculate_mmd(X, Y, gamma):
        XX = rbf_kernel(X, X, gamma)
        YY = rbf_kernel(Y, Y, gamma)
        XY = rbf_kernel(X, Y, gamma)
        return XX.mean() + YY.mean() - 2 * XY.mean()
gamma_val = 1 / (np.sqrt(2 * X_test.shape[1])**2)
def calculate_top_k(exp, gt, k=5):
        if exp.ndim == 2:  
                exp = np.mean(exp, axis=0)
        if gt.ndim == 2:
                gt = np.mean(gt, axis=0)

        exp_top_k = np.argsort(exp)[-k:]  
        gt_top_k = np.argsort(gt)[-k:]  
        correct_top_k = len(set(exp_top_k).intersection(set(gt_top_k)))
        return correct_top_k / k

In [18]:
values_gt = np.load(f'../metadata/german/ground_truth_shap_sage_results_0_1.npy', allow_pickle=True).item()
mmd_sobolev1 = calculate_mmd(X_test, X_test_sobolev1, gamma=gamma_val)
mae = None
top_k_score = None
gt_key_shap = 'ground_truth_shap_kernel'
gt_key_sage = 'ground_truth_sage_permutation'
if gt_key_shap in values_gt:
    values_gt_shap_sobolev1 = np.mean(np.array([values_gt[gt_key_shap][i] for i in range(1)]), axis=0)
    mae_shap_sobolev1 = np.mean(np.abs(exp_shap_sobolev1 - values_gt_shap_sobolev1))
    top_k_score_shap_sobolev1 = calculate_top_k(exp_shap_sobolev1, values_gt_shap_sobolev1, k=5)
if gt_key_sage in values_gt:
    values_gt_sage_sobolev1 = np.mean(np.array([values_gt[gt_key_sage][i] for i in range(1)]), axis=0)
    mae_sage_sobolev1 = np.mean(np.abs(exp_sage_sobolev1 - values_gt_sage_sobolev1))
    top_k_score_sage_sobolev1 = calculate_top_k(exp_sage_sobolev1, values_gt_sage_sobolev1, k=5)

row1 = {
    'dataset': "german",
    'repeat': 1,
    'method': f'cte_sobolev_1_shap', 
    'time_explanation': end_time_explanation_shap_sobolev1,
    'time_sample_choose': compressed_indices_sobolev1_time, 
    'n_original': X_test.shape[0],
    'n_sample': len(compressed_indices_sobolev1),
    'mmd': mmd_sobolev1,
    'mae': mae_shap_sobolev1,
    'top_k': top_k_score_shap_sobolev1
}
row2 = {
    'dataset': "german",
    'repeat': 1,
    'method': f'cte_sobolev_1_sage', 
    'time_explanation': end_time_explanation_sage_sobolev1,
    'time_sample_choose': compressed_indices_sobolev1_time, 
    'n_original': X_test.shape[0],
    'n_sample': len(compressed_indices_sobolev1),
    'mmd': mmd_sobolev1,
    'mae': mae_sage_sobolev1,
    'top_k': top_k_score_sage_sobolev1
}
times_sobolev1 = pd.concat([pd.DataFrame([row1]), pd.DataFrame([row2])])

In [23]:
mmd_sobolev3 = calculate_mmd(X_test, X_test_sobolev3, gamma=gamma_val)
mae = None
top_k_score = None
gt_key_shap = 'ground_truth_shap_kernel'
gt_key_sage = 'ground_truth_sage_permutation'
if gt_key_shap in values_gt:
    values_gt_shap_sobolev3 = np.mean(np.array([values_gt[gt_key_shap][i] for i in range(1)]), axis=0)
    mae_shap_sobolev3 = np.mean(np.abs(exp_shap_sobolev3 - values_gt_shap_sobolev3))
    top_k_score_shap_sobolev3 = calculate_top_k(exp_shap_sobolev3, values_gt_shap_sobolev3, k=5)
if gt_key_sage in values_gt:
    values_gt_sage_sobolev3 = np.mean(np.array([values_gt[gt_key_sage][i] for i in range(1)]), axis=0)
    mae_sage_sobolev3 = np.mean(np.abs(exp_sage_sobolev3 - values_gt_sage_sobolev3))
    top_k_score_sage_sobolev3 = calculate_top_k(exp_sage_sobolev3, values_gt_sage_sobolev3, k=5)

row1 = {
    'dataset': "german",
    'repeat': 1,
    'method': f'cte_sobolev_3_shap', 
    'time_explanation': end_time_explanation_shap_sobolev3,
    'time_sample_choose': compressed_indices_sobolev3_time, 
    'n_original': X_test.shape[0],
    'n_sample': len(compressed_indices_sobolev3),
    'mmd': mmd_sobolev3,
    'mae': mae_shap_sobolev3,
    'top_k': top_k_score_shap_sobolev3
}
row2 = {
    'dataset': "german",
    'repeat': 1,
    'method': f'cte_sobolev_3_sage', 
    'time_explanation': end_time_explanation_sage_sobolev3,
    'time_sample_choose': compressed_indices_sobolev3_time, 
    'n_original': X_test.shape[0],
    'n_sample': len(compressed_indices_sobolev3),
    'mmd': mmd_sobolev3,
    'mae': mae_sage_sobolev3,
    'top_k': top_k_score_sage_sobolev3
}
times_sobolev3 = pd.concat([pd.DataFrame([row1]), pd.DataFrame([row2])])

In [19]:
times_sobolev1

,dataset,repeat,method,time_explanation,time_sample_choose,n_original,n_sample,mmd,mae,top_k
0,german,1,cte_sobolev_1_shap,26.847223,0.003784,200,8,0.016532,0.011460,0.0
0,german,1,cte_sobolev_1_sage,94.199718,0.003784,200,8,0.016532,0.008553,0.4

In [24]:
times_sobolev3

,dataset,repeat,method,time_explanation,time_sample_choose,n_original,n_sample,mmd,mae,top_k
0,german,1,cte_sobolev_3_shap,26.354104,0.001106,200,8,0.028271,0.013507,0.2
0,german,1,cte_sobolev_3_sage,49.904897,0.001106,200,8,0.028271,0.015235,0.0

In [ ]:
dataset repeat         method       time_explanation   time_sample_choose  n_original  n_sample  mmd       mae        top_k
german   0           cte_shap           27.528821         0.00154614            200        8   0.0042569  0.0085143    0.0
german   0           cte_sage           71.990056         0.00154614            200        8   0.0042569  0.0119092    0.2

only gain - faster time_sample_choose, time_explanation for k=3, and lower mae for sage for k=1

### compas

In [25]:
_, loader_test = ReturnLoaders(data_name="compas", download=False, batch_size=128)
X_test = loader_test.dataset.data
y_test = loader_test.dataset.targets.to_numpy()
model = LoadModel(data_name="compas", ml_model="ann", pretrained=True)
model.eval()
predictions = model.predict(X_test)


start_time = time.time()
compressed_indices_sobolev1 = compress.compresspp_kt(X_test, kernel_type=b"sobolev", k_params=np.array([1.0]), seed=1)
compressed_indices_sobolev1_time = time.time() - start_time
X_test_sobolev1 = X_test[compressed_indices_sobolev1]
y_test_sobolev1 = y_test[compressed_indices_sobolev1]

start_time = time.time()
compressed_indices_sobolev3 = compress.compresspp_kt(X_test, kernel_type=b"sobolev", k_params=np.array([3.0]), seed=1)
compressed_indices_sobolev3_time = time.time() - start_time
X_test_sobolev3 = X_test[compressed_indices_sobolev3]
y_test_sobolev3 = y_test[compressed_indices_sobolev3]


start_time = time.time()
explainer = shap.KernelExplainer(lambda x: model.predict_proba(x)[:, 1], X_test_sobolev1, seed=1)
exp_shap_sobolev1 = explainer(X_test, silent=True).values
end_time_explanation_shap_sobolev1 = time.time() - start_time

start_time = time.time()
imputer = sage.MarginalImputer(model.predict_proba, X_test_sobolev1)
explainer = (sage.PermutationEstimator)(imputer, loss="cross entropy", random_state=1)
exp_sage_sobolev1 = explainer(X_test, y_test, bar=False, verbose=True).values
end_time_explanation_sage_sobolev1 = time.time() - start_time

start_time = time.time()
explainer = shap.KernelExplainer(lambda x: model.predict_proba(x)[:, 1], X_test_sobolev3, seed=1)
exp_shap_sobolev3 = explainer(X_test, silent=True).values
end_time_explanation_shap_sobolev3 = time.time() - start_time

start_time = time.time()
imputer = sage.MarginalImputer(model.predict_proba, X_test_sobolev3)
explainer = (sage.PermutationEstimator)(imputer, loss="cross entropy", random_state=1)
exp_sage_sobolev3 = explainer(X_test, y_test, bar=False, verbose=True).values
end_time_explanation_sage_sobolev3 = time.time() - start_time


values_gt = np.load(f'../metadata/compas/ground_truth_shap_sage_results_0_3.npy', allow_pickle=True).item()

mmd_sobolev1 = calculate_mmd(X_test, X_test_sobolev1, gamma=gamma_val)
mae = None
top_k_score = None
gt_key_shap = 'ground_truth_shap_kernel'
gt_key_sage = 'ground_truth_sage_permutation'
if gt_key_shap in values_gt:
    values_gt_shap_sobolev1 = np.mean(np.array([values_gt[gt_key_shap][i] for i in range(3)]), axis=0)
    mae_shap_sobolev1 = np.mean(np.abs(exp_shap_sobolev1 - values_gt_shap_sobolev1))
    top_k_score_shap_sobolev1 = calculate_top_k(exp_shap_sobolev1, values_gt_shap_sobolev1, k=5)
if gt_key_sage in values_gt:
    values_gt_sage_sobolev1 = np.mean(np.array([values_gt[gt_key_sage][i] for i in range(3)]), axis=0)
    mae_sage_sobolev1 = np.mean(np.abs(exp_sage_sobolev1 - values_gt_sage_sobolev1))
    top_k_score_sage_sobolev1 = calculate_top_k(exp_sage_sobolev1, values_gt_sage_sobolev1, k=5)

row1 = {
    'dataset': "compas",
    'repeat': 1,
    'method': f'cte_sobolev_1_shap', 
    'time_explanation': end_time_explanation_shap_sobolev1,
    'time_sample_choose': compressed_indices_sobolev1_time, 
    'n_original': X_test.shape[0],
    'n_sample': len(compressed_indices_sobolev1),
    'mmd': mmd_sobolev1,
    'mae': mae_shap_sobolev1,
    'top_k': top_k_score_shap_sobolev1
}
row2 = {
    'dataset': "compas",
    'repeat': 1,
    'method': f'cte_sobolev_1_sage', 
    'time_explanation': end_time_explanation_sage_sobolev1,
    'time_sample_choose': compressed_indices_sobolev1_time, 
    'n_original': X_test.shape[0],
    'n_sample': len(compressed_indices_sobolev1),
    'mmd': mmd_sobolev1,
    'mae': mae_sage_sobolev1,
    'top_k': top_k_score_sage_sobolev1
}
times_sobolev1_compas = pd.concat([pd.DataFrame([row1]), pd.DataFrame([row2])])

mmd_sobolev3 = calculate_mmd(X_test, X_test_sobolev3, gamma=gamma_val)
mae = None
top_k_score = None
gt_key_shap = 'ground_truth_shap_kernel'
gt_key_sage = 'ground_truth_sage_permutation'
if gt_key_shap in values_gt:
    values_gt_shap_sobolev3 = np.mean(np.array([values_gt[gt_key_shap][i] for i in range(3)]), axis=0)
    mae_shap_sobolev3 = np.mean(np.abs(exp_shap_sobolev3 - values_gt_shap_sobolev3))
    top_k_score_shap_sobolev3 = calculate_top_k(exp_shap_sobolev3, values_gt_shap_sobolev3, k=5)
if gt_key_sage in values_gt:
    values_gt_sage_sobolev3 = np.mean(np.array([values_gt[gt_key_sage][i] for i in range(3)]), axis=0)
    mae_sage_sobolev3 = np.mean(np.abs(exp_sage_sobolev3 - values_gt_sage_sobolev3))
    top_k_score_sage_sobolev3 = calculate_top_k(exp_sage_sobolev3, values_gt_sage_sobolev3, k=5)

row1 = {
    'dataset': "compas",
    'repeat': 1,
    'method': f'cte_sobolev_3_shap', 
    'time_explanation': end_time_explanation_shap_sobolev3,
    'time_sample_choose': compressed_indices_sobolev3_time, 
    'n_original': X_test.shape[0],
    'n_sample': len(compressed_indices_sobolev3),
    'mmd': mmd_sobolev3,
    'mae': mae_shap_sobolev3,
    'top_k': top_k_score_shap_sobolev3
}
row2 = {
    'dataset': "compas",
    'repeat': 1,
    'method': f'cte_sobolev_3_sage', 
    'time_explanation': end_time_explanation_sage_sobolev3,
    'time_sample_choose': compressed_indices_sobolev3_time, 
    'n_original': X_test.shape[0],
    'n_sample': len(compressed_indices_sobolev3),
    'mmd': mmd_sobolev3,
    'mae': mae_sage_sobolev3,
    'top_k': top_k_score_sage_sobolev3
}
times_sobolev3_compas = pd.concat([pd.DataFrame([row1]), pd.DataFrame([row2])])

StdDev Ratio = 0.3359 (Converge at 0.0250)
StdDev Ratio = 0.2865 (Converge at 0.0250)
StdDev Ratio = 0.2088 (Converge at 0.0250)
StdDev Ratio = 0.1803 (Converge at 0.0250)
StdDev Ratio = 0.1842 (Converge at 0.0250)
StdDev Ratio = 0.1832 (Converge at 0.0250)
StdDev Ratio = 0.1756 (Converge at 0.0250)
StdDev Ratio = 0.1574 (Converge at 0.0250)
StdDev Ratio = 0.1543 (Converge at 0.0250)
StdDev Ratio = 0.1316 (Converge at 0.0250)
StdDev Ratio = 0.1253 (Converge at 0.0250)
StdDev Ratio = 0.1156 (Converge at 0.0250)
StdDev Ratio = 0.1146 (Converge at 0.0250)
StdDev Ratio = 0.1139 (Converge at 0.0250)
StdDev Ratio = 0.1119 (Converge at 0.0250)
StdDev Ratio = 0.1078 (Converge at 0.0250)
StdDev Ratio = 0.1066 (Converge at 0.0250)
StdDev Ratio = 0.1042 (Converge at 0.0250)
StdDev Ratio = 0.1013 (Converge at 0.0250)
StdDev Ratio = 0.1022 (Converge at 0.0250)
StdDev Ratio = 0.1027 (Converge at 0.0250)
StdDev Ratio = 0.1006 (Converge at 0.0250)
StdDev Ratio = 0.0990 (Converge at 0.0250)
StdDev Ratio = 0.0958 (Converge at 0.0250)
StdDev Ratio = 0.0943 (Converge at 0.0250)
StdDev Ratio = 0.0922 (Converge at 0.0250)
StdDev Ratio = 0.0910 (Converge at 0.0250)
StdDev Ratio = 0.0901 (Converge at 0.0250)
StdDev Ratio = 0.0893 (Converge at 0.0250)
StdDev Ratio = 0.0882 (Converge at 0.0250)
StdDev Ratio = 0.0879 (Converge at 0.0250)
StdDev Ratio = 0.0870 (Converge at 0.0250)
StdDev Ratio = 0.0844 (Converge at 0.0250)
StdDev Ratio = 0.0830 (Converge at 0.0250)
StdDev Ratio = 0.0825 (Converge at 0.0250)
StdDev Ratio = 0.0813 (Converge at 0.0250)
StdDev Ratio = 0.0790 (Converge at 0.0250)
StdDev Ratio = 0.0766 (Converge at 0.0250)
StdDev Ratio = 0.0759 (Converge at 0.0250)
StdDev Ratio = 0.0756 (Converge at 0.0250)
StdDev Ratio = 0.0747 (Converge at 0.0250)
StdDev Ratio = 0.0737 (Converge at 0.0250)
StdDev Ratio = 0.0726 (Converge at 0.0250)
StdDev Ratio = 0.0718 (Converge at 0.0250)
StdDev Ratio = 0.0703 (Converge at 0.0250)
StdDev Ratio = 0.0693 (Converge at 0.0250)
StdDev Ratio = 0.0677 (Converge at 0.0250)
StdDev Ratio = 0.0664 (Converge at 0.0250)
StdDev Ratio = 0.0651 (Converge at 0.0250)
StdDev Ratio = 0.0647 (Converge at 0.0250)
StdDev Ratio = 0.0650 (Converge at 0.0250)
StdDev Ratio = 0.0639 (Converge at 0.0250)
StdDev Ratio = 0.0631 (Converge at 0.0250)
StdDev Ratio = 0.0627 (Converge at 0.0250)
StdDev Ratio = 0.0622 (Converge at 0.0250)
StdDev Ratio = 0.0623 (Converge at 0.0250)
StdDev Ratio = 0.0630 (Converge at 0.0250)
StdDev Ratio = 0.0620 (Converge at 0.0250)
StdDev Ratio = 0.0616 (Converge at 0.0250)
StdDev Ratio = 0.0604 (Converge at 0.0250)
StdDev Ratio = 0.0598 (Converge at 0.0250)
StdDev Ratio = 0.0592 (Converge at 0.0250)
StdDev Ratio = 0.0588 (Converge at 0.0250)
StdDev Ratio = 0.0584 (Converge at 0.0250)
StdDev Ratio = 0.0579 (Converge at 0.0250)
StdDev Ratio = 0.0570 (Converge at 0.0250)
StdDev Ratio = 0.0565 (Converge at 0.0250)
StdDev Ratio = 0.0559 (Converge at 0.0250)
StdDev Ratio = 0.0558 (Converge at 0.0250)
StdDev Ratio = 0.0556 (Converge at 0.0250)
StdDev Ratio = 0.0552 (Converge at 0.0250)
StdDev Ratio = 0.0546 (Converge at 0.0250)
StdDev Ratio = 0.0547 (Converge at 0.0250)
StdDev Ratio = 0.0542 (Converge at 0.0250)
StdDev Ratio = 0.0539 (Converge at 0.0250)
StdDev Ratio = 0.0538 (Converge at 0.0250)
StdDev Ratio = 0.0535 (Converge at 0.0250)
StdDev Ratio = 0.0532 (Converge at 0.0250)
StdDev Ratio = 0.0528 (Converge at 0.0250)
StdDev Ratio = 0.0525 (Converge at 0.0250)
StdDev Ratio = 0.0519 (Converge at 0.0250)
StdDev Ratio = 0.0515 (Converge at 0.0250)
StdDev Ratio = 0.0514 (Converge at 0.0250)
StdDev Ratio = 0.0512 (Converge at 0.0250)
StdDev Ratio = 0.0510 (Converge at 0.0250)
StdDev Ratio = 0.0507 (Converge at 0.0250)
StdDev Ratio = 0.0504 (Converge at 0.0250)
StdDev Ratio = 0.0501 (Converge at 0.0250)
StdDev Ratio = 0.0495 (Converge at 0.0250)
StdDev Ratio = 0.0493 (Converge at 0.0250)
StdDev Ratio = 0.0486 (Converge at 0.0250)
StdDev Ratio = 0.0484 (Converge at 0.0250)
StdDev Ratio = 0.0483 (Converge at 0.0250)
StdDev Ratio = 0.0483 (Converge at 0.0250)
StdDev Ratio = 0.0480 (Converge at 0.0250)
StdDev Ratio = 0.0477 (Converge at 0.0250)
StdDev Ratio = 0.0475 (Converge at 0.0250)
StdDev Ratio = 0.0472 (Converge at 0.0250)
StdDev Ratio = 0.0471 (Converge at 0.0250)
StdDev Ratio = 0.0469 (Converge at 0.0250)
StdDev Ratio = 0.0468 (Converge at 0.0250)
StdDev Ratio = 0.0464 (Converge at 0.0250)
StdDev Ratio = 0.0461 (Converge at 0.0250)
StdDev Ratio = 0.0464 (Converge at 0.0250)
StdDev Ratio = 0.0464 (Converge at 0.0250)
StdDev Ratio = 0.0462 (Converge at 0.0250)
StdDev Ratio = 0.0463 (Converge at 0.0250)
StdDev Ratio = 0.0460 (Converge at 0.0250)
StdDev Ratio = 0.0458 (Converge at 0.0250)
StdDev Ratio = 0.0457 (Converge at 0.0250)
StdDev Ratio = 0.0451 (Converge at 0.0250)
StdDev Ratio = 0.0448 (Converge at 0.0250)
StdDev Ratio = 0.0442 (Converge at 0.0250)
StdDev Ratio = 0.0441 (Converge at 0.0250)
StdDev Ratio = 0.0437 (Converge at 0.0250)
StdDev Ratio = 0.0438 (Converge at 0.0250)
StdDev Ratio = 0.0438 (Converge at 0.0250)
StdDev Ratio = 0.0435 (Converge at 0.0250)
StdDev Ratio = 0.0434 (Converge at 0.0250)
StdDev Ratio = 0.0431 (Converge at 0.0250)
StdDev Ratio = 0.0429 (Converge at 0.0250)
StdDev Ratio = 0.0431 (Converge at 0.0250)
StdDev Ratio = 0.0430 (Converge at 0.0250)
StdDev Ratio = 0.0428 (Converge at 0.0250)
StdDev Ratio = 0.0425 (Converge at 0.0250)
StdDev Ratio = 0.0421 (Converge at 0.0250)
StdDev Ratio = 0.0419 (Converge at 0.0250)
StdDev Ratio = 0.0418 (Converge at 0.0250)
StdDev Ratio = 0.0415 (Converge at 0.0250)
StdDev Ratio = 0.0413 (Converge at 0.0250)
StdDev Ratio = 0.0411 (Converge at 0.0250)
StdDev Ratio = 0.0407 (Converge at 0.0250)
StdDev Ratio = 0.0404 (Converge at 0.0250)
StdDev Ratio = 0.0402 (Converge at 0.0250)
StdDev Ratio = 0.0403 (Converge at 0.0250)
StdDev Ratio = 0.0400 (Converge at 0.0250)
StdDev Ratio = 0.0399 (Converge at 0.0250)
StdDev Ratio = 0.0396 (Converge at 0.0250)
StdDev Ratio = 0.0394 (Converge at 0.0250)
StdDev Ratio = 0.0393 (Converge at 0.0250)
StdDev Ratio = 0.0390 (Converge at 0.0250)
StdDev Ratio = 0.0389 (Converge at 0.0250)
StdDev Ratio = 0.0389 (Converge at 0.0250)
StdDev Ratio = 0.0387 (Converge at 0.0250)
StdDev Ratio = 0.0386 (Converge at 0.0250)
StdDev Ratio = 0.0383 (Converge at 0.0250)
StdDev Ratio = 0.0382 (Converge at 0.0250)
StdDev Ratio = 0.0379 (Converge at 0.0250)
StdDev Ratio = 0.0379 (Converge at 0.0250)
StdDev Ratio = 0.0378 (Converge at 0.0250)
StdDev Ratio = 0.0377 (Converge at 0.0250)
StdDev Ratio = 0.0376 (Converge at 0.0250)
StdDev Ratio = 0.0375 (Converge at 0.0250)
StdDev Ratio = 0.0375 (Converge at 0.0250)
StdDev Ratio = 0.0373 (Converge at 0.0250)
StdDev Ratio = 0.0371 (Converge at 0.0250)
StdDev Ratio = 0.0370 (Converge at 0.0250)
StdDev Ratio = 0.0370 (Converge at 0.0250)
StdDev Ratio = 0.0369 (Converge at 0.0250)
StdDev Ratio = 0.0368 (Converge at 0.0250)
StdDev Ratio = 0.0366 (Converge at 0.0250)
StdDev Ratio = 0.0365 (Converge at 0.0250)
StdDev Ratio = 0.0363 (Converge at 0.0250)
StdDev Ratio = 0.0361 (Converge at 0.0250)
StdDev Ratio = 0.0361 (Converge at 0.0250)
StdDev Ratio = 0.0361 (Converge at 0.0250)
StdDev Ratio = 0.0360 (Converge at 0.0250)
StdDev Ratio = 0.0359 (Converge at 0.0250)
StdDev Ratio = 0.0358 (Converge at 0.0250)
StdDev Ratio = 0.0358 (Converge at 0.0250)
StdDev Ratio = 0.0357 (Converge at 0.0250)
StdDev Ratio = 0.0355 (Converge at 0.0250)
StdDev Ratio = 0.0354 (Converge at 0.0250)
StdDev Ratio = 0.0352 (Converge at 0.0250)
StdDev Ratio = 0.0350 (Converge at 0.0250)
StdDev Ratio = 0.0348 (Converge at 0.0250)
StdDev Ratio = 0.0347 (Converge at 0.0250)
StdDev Ratio = 0.0346 (Converge at 0.0250)
StdDev Ratio = 0.0344 (Converge at 0.0250)
StdDev Ratio = 0.0343 (Converge at 0.0250)
StdDev Ratio = 0.0342 (Converge at 0.0250)
StdDev Ratio = 0.0341 (Converge at 0.0250)
StdDev Ratio = 0.0340 (Converge at 0.0250)
StdDev Ratio = 0.0340 (Converge at 0.0250)
StdDev Ratio = 0.0338 (Converge at 0.0250)
StdDev Ratio = 0.0337 (Converge at 0.0250)
StdDev Ratio = 0.0336 (Converge at 0.0250)
StdDev Ratio = 0.0335 (Converge at 0.0250)
StdDev Ratio = 0.0334 (Converge at 0.0250)
StdDev Ratio = 0.0333 (Converge at 0.0250)
StdDev Ratio = 0.0332 (Converge at 0.0250)
StdDev Ratio = 0.0331 (Converge at 0.0250)
StdDev Ratio = 0.0331 (Converge at 0.0250)
StdDev Ratio = 0.0329 (Converge at 0.0250)
StdDev Ratio = 0.0329 (Converge at 0.0250)
StdDev Ratio = 0.0329 (Converge at 0.0250)
StdDev Ratio = 0.0329 (Converge at 0.0250)
StdDev Ratio = 0.0329 (Converge at 0.0250)
StdDev Ratio = 0.0329 (Converge at 0.0250)
StdDev Ratio = 0.0329 (Converge at 0.0250)
StdDev Ratio = 0.0328 (Converge at 0.0250)
StdDev Ratio = 0.0327 (Converge at 0.0250)
StdDev Ratio = 0.0326 (Converge at 0.0250)
StdDev Ratio = 0.0325 (Converge at 0.0250)
StdDev Ratio = 0.0325 (Converge at 0.0250)
StdDev Ratio = 0.0324 (Converge at 0.0250)
StdDev Ratio = 0.0322 (Converge at 0.0250)
StdDev Ratio = 0.0321 (Converge at 0.0250)
StdDev Ratio = 0.0320 (Converge at 0.0250)
StdDev Ratio = 0.0319 (Converge at 0.0250)
StdDev Ratio = 0.0319 (Converge at 0.0250)
StdDev Ratio = 0.0319 (Converge at 0.0250)
StdDev Ratio = 0.0319 (Converge at 0.0250)
StdDev Ratio = 0.0318 (Converge at 0.0250)
StdDev Ratio = 0.0318 (Converge at 0.0250)
StdDev Ratio = 0.0316 (Converge at 0.0250)
StdDev Ratio = 0.0314 (Converge at 0.0250)
StdDev Ratio = 0.0313 (Converge at 0.0250)
StdDev Ratio = 0.0312 (Converge at 0.0250)
StdDev Ratio = 0.0311 (Converge at 0.0250)
StdDev Ratio = 0.0310 (Converge at 0.0250)
StdDev Ratio = 0.0309 (Converge at 0.0250)
StdDev Ratio = 0.0309 (Converge at 0.0250)
StdDev Ratio = 0.0307 (Converge at 0.0250)
StdDev Ratio = 0.0307 (Converge at 0.0250)
StdDev Ratio = 0.0306 (Converge at 0.0250)
StdDev Ratio = 0.0304 (Converge at 0.0250)
StdDev Ratio = 0.0303 (Converge at 0.0250)
StdDev Ratio = 0.0303 (Converge at 0.0250)
StdDev Ratio = 0.0302 (Converge at 0.0250)
StdDev Ratio = 0.0301 (Converge at 0.0250)
StdDev Ratio = 0.0301 (Converge at 0.0250)
StdDev Ratio = 0.0301 (Converge at 0.0250)
StdDev Ratio = 0.0300 (Converge at 0.0250)
StdDev Ratio = 0.0300 (Converge at 0.0250)
StdDev Ratio = 0.0299 (Converge at 0.0250)
StdDev Ratio = 0.0299 (Converge at 0.0250)
StdDev Ratio = 0.0299 (Converge at 0.0250)
StdDev Ratio = 0.0298 (Converge at 0.0250)
StdDev Ratio = 0.0298 (Converge at 0.0250)
StdDev Ratio = 0.0297 (Converge at 0.0250)
StdDev Ratio = 0.0296 (Converge at 0.0250)
StdDev Ratio = 0.0296 (Converge at 0.0250)
StdDev Ratio = 0.0295 (Converge at 0.0250)
StdDev Ratio = 0.0295 (Converge at 0.0250)
StdDev Ratio = 0.0295 (Converge at 0.0250)
StdDev Ratio = 0.0294 (Converge at 0.0250)
StdDev Ratio = 0.0294 (Converge at 0.0250)
StdDev Ratio = 0.0294 (Converge at 0.0250)
StdDev Ratio = 0.0294 (Converge at 0.0250)
StdDev Ratio = 0.0294 (Converge at 0.0250)
StdDev Ratio = 0.0294 (Converge at 0.0250)
StdDev Ratio = 0.0293 (Converge at 0.0250)
StdDev Ratio = 0.0293 (Converge at 0.0250)
StdDev Ratio = 0.0293 (Converge at 0.0250)
StdDev Ratio = 0.0293 (Converge at 0.0250)
StdDev Ratio = 0.0292 (Converge at 0.0250)
StdDev Ratio = 0.0292 (Converge at 0.0250)
StdDev Ratio = 0.0291 (Converge at 0.0250)
StdDev Ratio = 0.0291 (Converge at 0.0250)
StdDev Ratio = 0.0290 (Converge at 0.0250)
StdDev Ratio = 0.0290 (Converge at 0.0250)
StdDev Ratio = 0.0289 (Converge at 0.0250)
StdDev Ratio = 0.0289 (Converge at 0.0250)
StdDev Ratio = 0.0288 (Converge at 0.0250)
StdDev Ratio = 0.0287 (Converge at 0.0250)
StdDev Ratio = 0.0287 (Converge at 0.0250)
StdDev Ratio = 0.0287 (Converge at 0.0250)
StdDev Ratio = 0.0285 (Converge at 0.0250)
StdDev Ratio = 0.0285 (Converge at 0.0250)
StdDev Ratio = 0.0285 (Converge at 0.0250)
StdDev Ratio = 0.0285 (Converge at 0.0250)
StdDev Ratio = 0.0284 (Converge at 0.0250)
StdDev Ratio = 0.0284 (Converge at 0.0250)
StdDev Ratio = 0.0283 (Converge at 0.0250)
StdDev Ratio = 0.0282 (Converge at 0.0250)
StdDev Ratio = 0.0281 (Converge at 0.0250)
StdDev Ratio = 0.0280 (Converge at 0.0250)
StdDev Ratio = 0.0279 (Converge at 0.0250)
StdDev Ratio = 0.0279 (Converge at 0.0250)
StdDev Ratio = 0.0279 (Converge at 0.0250)
StdDev Ratio = 0.0278 (Converge at 0.0250)
StdDev Ratio = 0.0277 (Converge at 0.0250)
StdDev Ratio = 0.0277 (Converge at 0.0250)
StdDev Ratio = 0.0277 (Converge at 0.0250)
StdDev Ratio = 0.0276 (Converge at 0.0250)
StdDev Ratio = 0.0276 (Converge at 0.0250)
StdDev Ratio = 0.0275 (Converge at 0.0250)
StdDev Ratio = 0.0275 (Converge at 0.0250)
StdDev Ratio = 0.0274 (Converge at 0.0250)
StdDev Ratio = 0.0273 (Converge at 0.0250)
StdDev Ratio = 0.0272 (Converge at 0.0250)
StdDev Ratio = 0.0271 (Converge at 0.0250)
StdDev Ratio = 0.0271 (Converge at 0.0250)
StdDev Ratio = 0.0271 (Converge at 0.0250)
StdDev Ratio = 0.0270 (Converge at 0.0250)
StdDev Ratio = 0.0270 (Converge at 0.0250)
StdDev Ratio = 0.0270 (Converge at 0.0250)
StdDev Ratio = 0.0269 (Converge at 0.0250)
StdDev Ratio = 0.0269 (Converge at 0.0250)
StdDev Ratio = 0.0269 (Converge at 0.0250)
StdDev Ratio = 0.0268 (Converge at 0.0250)
StdDev Ratio = 0.0268 (Converge at 0.0250)
StdDev Ratio = 0.0268 (Converge at 0.0250)
StdDev Ratio = 0.0267 (Converge at 0.0250)
StdDev Ratio = 0.0266 (Converge at 0.0250)
StdDev Ratio = 0.0266 (Converge at 0.0250)
StdDev Ratio = 0.0266 (Converge at 0.0250)
StdDev Ratio = 0.0265 (Converge at 0.0250)
StdDev Ratio = 0.0264 (Converge at 0.0250)
StdDev Ratio = 0.0264 (Converge at 0.0250)
StdDev Ratio = 0.0262 (Converge at 0.0250)
StdDev Ratio = 0.0262 (Converge at 0.0250)
StdDev Ratio = 0.0262 (Converge at 0.0250)
StdDev Ratio = 0.0262 (Converge at 0.0250)
StdDev Ratio = 0.0262 (Converge at 0.0250)
StdDev Ratio = 0.0261 (Converge at 0.0250)
StdDev Ratio = 0.0261 (Converge at 0.0250)
StdDev Ratio = 0.0261 (Converge at 0.0250)
StdDev Ratio = 0.0260 (Converge at 0.0250)
StdDev Ratio = 0.0259 (Converge at 0.0250)
StdDev Ratio = 0.0259 (Converge at 0.0250)
StdDev Ratio = 0.0259 (Converge at 0.0250)
StdDev Ratio = 0.0258 (Converge at 0.0250)
StdDev Ratio = 0.0258 (Converge at 0.0250)
StdDev Ratio = 0.0258 (Converge at 0.0250)
StdDev Ratio = 0.0257 (Converge at 0.0250)
StdDev Ratio = 0.0256 (Converge at 0.0250)
StdDev Ratio = 0.0256 (Converge at 0.0250)
StdDev Ratio = 0.0256 (Converge at 0.0250)
StdDev Ratio = 0.0255 (Converge at 0.0250)
StdDev Ratio = 0.0255 (Converge at 0.0250)
StdDev Ratio = 0.0255 (Converge at 0.0250)
StdDev Ratio = 0.0255 (Converge at 0.0250)
StdDev Ratio = 0.0254 (Converge at 0.0250)
StdDev Ratio = 0.0253 (Converge at 0.0250)
StdDev Ratio = 0.0252 (Converge at 0.0250)
StdDev Ratio = 0.0252 (Converge at 0.0250)
StdDev Ratio = 0.0252 (Converge at 0.0250)
StdDev Ratio = 0.0252 (Converge at 0.0250)
StdDev Ratio = 0.0251 (Converge at 0.0250)
StdDev Ratio = 0.0251 (Converge at 0.0250)
StdDev Ratio = 0.0251 (Converge at 0.0250)
StdDev Ratio = 0.0251 (Converge at 0.0250)
StdDev Ratio = 0.0250 (Converge at 0.0250)
StdDev Ratio = 0.0250 (Converge at 0.0250)
StdDev Ratio = 0.0250 (Converge at 0.0250)
Detected convergence
StdDev Ratio = 0.4261 (Converge at 0.0250)
StdDev Ratio = 0.2211 (Converge at 0.0250)
StdDev Ratio = 0.2026 (Converge at 0.0250)
StdDev Ratio = 0.1881 (Converge at 0.0250)
StdDev Ratio = 0.1591 (Converge at 0.0250)
StdDev Ratio = 0.1439 (Converge at 0.0250)
StdDev Ratio = 0.1409 (Converge at 0.0250)
StdDev Ratio = 0.1370 (Converge at 0.0250)
StdDev Ratio = 0.1218 (Converge at 0.0250)
StdDev Ratio = 0.1274 (Converge at 0.0250)
StdDev Ratio = 0.1190 (Converge at 0.0250)
StdDev Ratio = 0.1166 (Converge at 0.0250)
StdDev Ratio = 0.1095 (Converge at 0.0250)
StdDev Ratio = 0.1022 (Converge at 0.0250)
StdDev Ratio = 0.1002 (Converge at 0.0250)
StdDev Ratio = 0.0982 (Converge at 0.0250)
StdDev Ratio = 0.0987 (Converge at 0.0250)
StdDev Ratio = 0.0946 (Converge at 0.0250)
StdDev Ratio = 0.0945 (Converge at 0.0250)
StdDev Ratio = 0.0893 (Converge at 0.0250)
StdDev Ratio = 0.0852 (Converge at 0.0250)
StdDev Ratio = 0.0837 (Converge at 0.0250)
StdDev Ratio = 0.0821 (Converge at 0.0250)
StdDev Ratio = 0.0811 (Converge at 0.0250)
StdDev Ratio = 0.0785 (Converge at 0.0250)
StdDev Ratio = 0.0760 (Converge at 0.0250)
StdDev Ratio = 0.0741 (Converge at 0.0250)
StdDev Ratio = 0.0726 (Converge at 0.0250)
StdDev Ratio = 0.0715 (Converge at 0.0250)
StdDev Ratio = 0.0701 (Converge at 0.0250)
StdDev Ratio = 0.0678 (Converge at 0.0250)
StdDev Ratio = 0.0657 (Converge at 0.0250)
StdDev Ratio = 0.0657 (Converge at 0.0250)
StdDev Ratio = 0.0654 (Converge at 0.0250)
StdDev Ratio = 0.0650 (Converge at 0.0250)
StdDev Ratio = 0.0641 (Converge at 0.0250)
StdDev Ratio = 0.0627 (Converge at 0.0250)
StdDev Ratio = 0.0631 (Converge at 0.0250)
StdDev Ratio = 0.0621 (Converge at 0.0250)
StdDev Ratio = 0.0612 (Converge at 0.0250)
StdDev Ratio = 0.0603 (Converge at 0.0250)
StdDev Ratio = 0.0596 (Converge at 0.0250)
StdDev Ratio = 0.0588 (Converge at 0.0250)
StdDev Ratio = 0.0580 (Converge at 0.0250)
StdDev Ratio = 0.0578 (Converge at 0.0250)
StdDev Ratio = 0.0574 (Converge at 0.0250)
StdDev Ratio = 0.0571 (Converge at 0.0250)
StdDev Ratio = 0.0567 (Converge at 0.0250)
StdDev Ratio = 0.0562 (Converge at 0.0250)
StdDev Ratio = 0.0556 (Converge at 0.0250)
StdDev Ratio = 0.0545 (Converge at 0.0250)
StdDev Ratio = 0.0535 (Converge at 0.0250)
StdDev Ratio = 0.0533 (Converge at 0.0250)
StdDev Ratio = 0.0524 (Converge at 0.0250)
StdDev Ratio = 0.0524 (Converge at 0.0250)
StdDev Ratio = 0.0514 (Converge at 0.0250)
StdDev Ratio = 0.0503 (Converge at 0.0250)
StdDev Ratio = 0.0497 (Converge at 0.0250)
StdDev Ratio = 0.0494 (Converge at 0.0250)
StdDev Ratio = 0.0496 (Converge at 0.0250)
StdDev Ratio = 0.0494 (Converge at 0.0250)
StdDev Ratio = 0.0492 (Converge at 0.0250)
StdDev Ratio = 0.0490 (Converge at 0.0250)
StdDev Ratio = 0.0485 (Converge at 0.0250)
StdDev Ratio = 0.0481 (Converge at 0.0250)
StdDev Ratio = 0.0476 (Converge at 0.0250)
StdDev Ratio = 0.0476 (Converge at 0.0250)
StdDev Ratio = 0.0474 (Converge at 0.0250)
StdDev Ratio = 0.0473 (Converge at 0.0250)
StdDev Ratio = 0.0468 (Converge at 0.0250)
StdDev Ratio = 0.0466 (Converge at 0.0250)
StdDev Ratio = 0.0461 (Converge at 0.0250)
StdDev Ratio = 0.0455 (Converge at 0.0250)
StdDev Ratio = 0.0451 (Converge at 0.0250)
StdDev Ratio = 0.0446 (Converge at 0.0250)
StdDev Ratio = 0.0438 (Converge at 0.0250)
StdDev Ratio = 0.0435 (Converge at 0.0250)
StdDev Ratio = 0.0430 (Converge at 0.0250)
StdDev Ratio = 0.0429 (Converge at 0.0250)
StdDev Ratio = 0.0425 (Converge at 0.0250)
StdDev Ratio = 0.0427 (Converge at 0.0250)
StdDev Ratio = 0.0427 (Converge at 0.0250)
StdDev Ratio = 0.0423 (Converge at 0.0250)
StdDev Ratio = 0.0421 (Converge at 0.0250)
StdDev Ratio = 0.0417 (Converge at 0.0250)
StdDev Ratio = 0.0415 (Converge at 0.0250)
StdDev Ratio = 0.0410 (Converge at 0.0250)
StdDev Ratio = 0.0409 (Converge at 0.0250)
StdDev Ratio = 0.0408 (Converge at 0.0250)
StdDev Ratio = 0.0406 (Converge at 0.0250)
StdDev Ratio = 0.0407 (Converge at 0.0250)
StdDev Ratio = 0.0402 (Converge at 0.0250)
StdDev Ratio = 0.0400 (Converge at 0.0250)
StdDev Ratio = 0.0395 (Converge at 0.0250)
StdDev Ratio = 0.0394 (Converge at 0.0250)
StdDev Ratio = 0.0394 (Converge at 0.0250)
StdDev Ratio = 0.0389 (Converge at 0.0250)
StdDev Ratio = 0.0390 (Converge at 0.0250)
StdDev Ratio = 0.0388 (Converge at 0.0250)
StdDev Ratio = 0.0387 (Converge at 0.0250)
StdDev Ratio = 0.0384 (Converge at 0.0250)
StdDev Ratio = 0.0385 (Converge at 0.0250)
StdDev Ratio = 0.0386 (Converge at 0.0250)
StdDev Ratio = 0.0384 (Converge at 0.0250)
StdDev Ratio = 0.0381 (Converge at 0.0250)
StdDev Ratio = 0.0377 (Converge at 0.0250)
StdDev Ratio = 0.0374 (Converge at 0.0250)
StdDev Ratio = 0.0372 (Converge at 0.0250)
StdDev Ratio = 0.0369 (Converge at 0.0250)
StdDev Ratio = 0.0368 (Converge at 0.0250)
StdDev Ratio = 0.0368 (Converge at 0.0250)
StdDev Ratio = 0.0367 (Converge at 0.0250)
StdDev Ratio = 0.0368 (Converge at 0.0250)
StdDev Ratio = 0.0366 (Converge at 0.0250)
StdDev Ratio = 0.0364 (Converge at 0.0250)
StdDev Ratio = 0.0361 (Converge at 0.0250)
StdDev Ratio = 0.0359 (Converge at 0.0250)

In [26]:
times_sobolev1_compas

,dataset,repeat,method,time_explanation,time_sample_choose,n_original,n_sample,mmd,mae,top_k
0,compas,1,cte_sobolev_1_shap,25.986105,0.001179,1235,32,0.00029,0.004541,0.6
0,compas,1,cte_sobolev_1_sage,155.155672,0.001179,1235,32,0.00029,0.014366,1.0

In [27]:
times_sobolev3_compas

,dataset,repeat,method,time_explanation,time_sample_choose,n_original,n_sample,mmd,mae,top_k
0,compas,1,cte_sobolev_3_shap,25.869481,0.000784,1235,32,0.000846,0.008349,0.6
0,compas,1,cte_sobolev_3_sage,105.129433,0.000784,1235,32,0.000846,0.030518,0.8

In [ ]:
dataset repeat  method     time_explanation  time_sample_choose   n_original  n_sample   mmd            mae       top_k
compas   0       cte_shap   26.06677484     0.02332592            1235         32       0.000165079   0.00313477   0.6
compas   0       cte_sage   209.8438327     0.02332592            1235         32       0.000165079   0.01233301   1.0

gain - shorter explanation time, time_sample_choose especially for sage; lower mmd gor k=3, lower mae for sage k=3

### Theory 
The Sobolev kernel focuses on a limited function class (with potentially faster computation and simpler interpretation). The Gaussian kernel covers a much richer function class, potentially giving better compression fidelity overall, but in regimes where that extra smoothness isn’t needed, it might not yield significantly better results than the Sobolev kernel.